"""Tests for benchmarks/make_tables.py: the paper's tables are computed from
raw runs, so the arithmetic is checked here on a small synthetic result set."""

import csv
import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "benchmarks"))

import make_tables as mt  # noqa: E402

FIELDS = ["experiment", "engine", "mode", "workers", "resp_size", "max_batch", "handler_work",
          "conns", "status", "rps", "requests", "lat_p50_ms", "lat_p99_ms", "server_cpu_pct",
          "client_cpu_pct", "socket_errors", "srv_requests", "srv_syscalls", "srv_enters",
          "srv_completions", "srv_gil", "transfer_mb_s", "srv_handler_calls",
          "srv_gil_hold_ns", "srv_gil_wait_ns", "srv_gil_acquires", "srv_gil_releases",
          "srv_nvcsw"]


def write_folder(root, name, experiment, interpreter, rows, nproc=4, docker_opts="",
                 image="uringpy:abcdef0", driver="abcdef0123", day="2026-10-07"):
    d = root / name
    d.mkdir()
    (d / "meta.json").write_text(json.dumps(
        {"experiment": experiment, "started_utc": day + "T01:00:00+00:00",
         "server": {"interpreter": interpreter, "nproc": str(nproc), "image": image},
         "client": {"git_commit": driver},
         "params": {"duration": 20, "warmup": 5, "docker_opts": docker_opts}}))
    with open(d / "runs.csv", "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=FIELDS)
        w.writeheader()
        for r in rows:
            w.writerow({"experiment": experiment, "resp_size": 13, "max_batch": 0,
                        "handler_work": 0, "status": "ok", **r})


def runs(engine, mode, workers, values, **extra):
    return [{"engine": engine, "mode": mode, "workers": workers, "rps": v, **extra}
            for v in values]


def make_results(tmp_path):
    rows = (runs("uringpy", "thread", 1, [100e3, 102e3, 98e3], server_cpu_pct=25, srv_gil="on",
                 srv_requests=1000, srv_syscalls=10, srv_enters=10, srv_completions=2000)
            + runs("uringpy", "thread", 4, [300e3, 300e3, 300e3], server_cpu_pct=100, srv_gil="on")
            + [{"engine": "uringpy", "mode": "thread", "workers": 4, "rps": "",
                "status": "no-start"}])
    write_folder(tmp_path, "scaling-a", "scaling", "3.14.7 gil_on", rows)
    write_folder(tmp_path, "scaling-b", "scaling", "3.14.7 gil_OFF",
                 runs("uringpy", "thread", 1, [90e3, 90e3], srv_gil="off"))
    (tmp_path / "not-a-result").mkdir()
    return mt.Data(*mt.load(str(tmp_path)))


def test_load_groups_by_gil_and_skips_failed_runs(tmp_path):
    d = make_results(tmp_path)
    c1 = d.get("scaling", "on", "uringpy", "thread", 1)
    c4 = d.get("scaling", "on", "uringpy", "thread", 4)
    assert c1.n == 3 and abs(c1.mean - 100e3) < 1e-6
    assert c4.n == 3 and c4.failed == 1          # the failed run is counted, not averaged
    assert d.get("scaling", "off", "uringpy", "thread", 1).n == 2
    assert [f["gil"] for f in d.folders] == ["on", "off"]


def test_derived_quantities(tmp_path):
    d = make_results(tmp_path)
    c1 = d.get("scaling", "on", "uringpy", "thread", 1)
    c4 = d.get("scaling", "on", "uringpy", "thread", 4)
    assert c1.busy_cores == 1.0 and c4.busy_cores == 4.0     # 25% and 100% of 4 cores
    assert abs(c1.per_core - 100e3) < 1e-6
    assert abs(mt._efficiency(c1, c4) - 0.75) < 1e-9          # 75k per core / 100k per core
    assert c1.syscalls_per_request == 30 / 3000
    assert c1.completions_per_enter == 200.0
    # half-width: t(0.975, 2) * s / sqrt(3) with s = 2000
    assert abs(c1.hw - 4.303 * 2000 / 3 ** 0.5) < 1e-6


def test_tables_are_written_and_carry_the_numbers(tmp_path):
    d = make_results(tmp_path)
    tex = mt.tab_scaling(d)
    assert "\\label{tab:scaling}" in tex
    assert "100.0 $\\pm$ 5.0" in tex and "300.0 $\\pm$ $<$0.1" in tex
    assert "3.00 $\\pm$" in tex                    # S_4
    assert mt.tab_app(d) is None                   # no data for that experiment
    out = tmp_path / "out"
    assert mt.main(["--results", str(tmp_path), "--out", str(out)]) == 0
    assert (out / "tab_scaling.tex").read_text().startswith("% Generated by")
    assert not (out / "tab_app.tex").exists()


def test_handler_table_derives_f_and_bound(tmp_path):
    def cell(engine, mode, workers, rps, **extra):
        return [{"engine": engine, "mode": mode, "workers": workers, "rps": v,
                 "handler_work": 300, "srv_gil": "on", **extra} for v in (rps, rps)]
    rows = (cell("uringpy-app", "thread", 1, 50e3, srv_handler_calls=1000,
                 srv_gil_hold_ns=10_000_000, srv_gil_wait_ns=0, srv_gil_acquires=1000)
            + cell("uringpy-app", "thread", 2, 75e3)
            + cell("uringpy-app", "thread", 4, 80e3, srv_handler_calls=1000,
                   srv_gil_hold_ns=12_000_000, srv_gil_wait_ns=30_000_000,
                   srv_gil_acquires=250)
            + cell("uringpy-app", "process", 1, 50e3) + cell("uringpy-app", "process", 4, 150e3))
    write_folder(tmp_path, "handler-a", "handler", "3.14.7 gil_on", rows)
    d = mt.Data(*mt.load(str(tmp_path)))
    t1 = d.get("handler", "on", "uringpy-app", "thread", 1, work=300)
    t4 = d.get("handler", "on", "uringpy-app", "thread", 4, work=300)
    assert t1.gil_hold_us == 10.0                 # 10 ms over 1000 calls
    assert t4.gil_wait_us == 30.0 and t4.acquires_per_request == 0.25
    tex = mt.tab_handler(d)
    # t_p = 10 us at 50k req/s -> f = 0.50 -> bound 2.00; S_2 = 1.50, S_4 = 1.60, processes 3.00
    row = next(line for line in tex.splitlines() if line.startswith("request & 300"))
    assert "& 10.00 & 0.50 & 2.00 &" in row
    assert "1.50 $\\pm$" in row and "1.60 $\\pm$" in row and "3.00 $\\pm$" in row
    # at four threads: hold 12 us, wait 30 us, 0.25 acquisitions per call,
    # GIL utilisation 12 us * 80k req/s = 0.96
    assert row.rstrip(" \\").endswith("& 12.00 & 30.00 & 0.250 & 0.96")


def test_handoffs_and_context_switches_per_request(tmp_path):
    def cell(engine, workers, rps, **extra):
        return [{"engine": engine, "mode": "thread", "workers": workers, "rps": v,
                 "srv_gil": "on", **extra} for v in (rps, rps)]
    rows = (
        # loop in Python: 2 GIL releases and 2 context switches per request
        cell("py-epoll", 1, 100e3, srv_requests=1000, srv_syscalls=2000, srv_gil_releases=2000,
             srv_nvcsw=10)
        + cell("py-epoll", 4, 60e3, srv_requests=1000, srv_syscalls=2000, srv_gil_releases=2000,
               srv_nvcsw=2000)
        # the control: same system calls, 1 release per 50 requests
        + cell("py-epoll-batch", 1, 120e3, srv_requests=1000, srv_syscalls=2000,
               srv_gil_releases=20, srv_nvcsw=10)
        + cell("py-epoll-batch", 4, 288e3, srv_requests=1000, srv_syscalls=2000,
               srv_gil_releases=20, srv_nvcsw=5)
        # a C reactor without a handler never takes the GIL
        + cell("uringpy", 1, 140e3, srv_requests=1000, srv_syscalls=10)
        + cell("uringpy", 4, 322e3, srv_requests=1000, srv_syscalls=20)
        # a runtime that does not count its requests: 25 s of life at 40k req/s
        + cell("asyncio", 4, 40e3, srv_nvcsw=2_000_000))
    write_folder(tmp_path, "factorial-a", "factorial", "3.14.7 gil_on", rows)
    d = mt.Data(*mt.load(str(tmp_path)), results_dir=str(tmp_path))
    slow = d.get("factorial", "on", "py-epoll", "thread", 4)
    fast = d.get("factorial", "on", "py-epoll-batch", "thread", 4)
    assert slow.handoffs == 2.0 and fast.handoffs == 0.02
    assert slow.syscalls_per_request == fast.syscalls_per_request == 2.0
    assert slow.csw == 2.0 and fast.csw == 0.005
    assert d.get("factorial", "on", "uringpy", "thread", 4).handoffs == 0.0
    base = d.get("factorial", "on", "asyncio", "thread", 4)
    assert base.handoffs != base.handoffs                    # nan: not counted
    assert base.csw == 2_000_000 / (40e3 * 25)               # estimated from wrk's count

    tex = mt.tab_factorial(d)
    row = next(line for line in tex.splitlines() if line.startswith("\\code{py-epoll-batch}"))
    assert "2.40 $\\pm$" in row and "& 2.000 & 0.020 & 0.005 &" in row
    assert "mathrm{ft}" not in tex                 # no free-threaded runs, no such column
    assert all(line.count(" & ") == 11 for line in tex.splitlines() if line.startswith("\\code"))
    effects = mt.tab_effects(d)
    assert "GIL releases (" in effects and "4.80 $\\pm$" in effects   # 288k over 60k

    values = mt.numbers(d)
    assert values["S:factorial/g/py-epoll-batch/thread/4"] == "2.40"
    assert values["ho:factorial/g/py-epoll/thread/4"] == "2.000"
    assert values["x:factorial/g/uringpy/thread/4"] == "322.0"
    assert values["r:handoff-epoll/4"] == "4.80"
    assert values["meta:runs"] == "14" and values["meta:failed"] == "0"
    assert "\\@namedef{v@r:handoff-epoll/4}{4.80}" in mt.numbers_tex(values)

    # the figure plots scaling against context switches per request
    fig = mt.fig_handoffs(d)
    assert "\\label{fig:handoffs}" in fig and "(0.005,2.4)" in fig and "(2,0.6)" in fig

    paper = tmp_path / "paper.tex"
    paper.write_text("a $\\V{S:factorial/g/py-epoll/thread/4}$ b \\V{no:such/key}")
    assert mt.check_keys(str(paper), values) == ["no:such/key"]

    # the README block is generated from the same runs and spliced between markers
    block = mt.headline_md(d)
    assert "`py-epoll-batch`) | 2.00 | 0.020 | 0.005 | 288.0 ± <0.1 | 2.40× | n/a |" in block
    assert block.startswith(mt.README_START) and block.rstrip().endswith(mt.README_END)
    readme = tmp_path / "README.md"
    readme.write_text("intro\n" + mt.README_START + "\nold\n" + mt.README_END + "\ntail\n")
    assert mt.splice_readme(str(readme), block) is True
    text = readme.read_text()
    assert text.startswith("intro\n" + mt.README_START) and text.endswith(mt.README_END + "\ntail\n")
    assert "old" not in text and mt.splice_readme(str(readme), block) is False

    # with runs of the free-threaded build the table gains their scaling
    free = [dict(r, srv_gil="off") for r in cell("py-epoll", 1, 100e3) + cell("py-epoll", 4, 230e3)]
    write_folder(tmp_path, "factorial-b", "factorial", "3.14.7 gil_OFF", free)
    d = mt.Data(*mt.load(str(tmp_path)), results_dir=str(tmp_path))
    tex = mt.tab_factorial(d)
    row = next(line for line in tex.splitlines() if line.startswith("\\code{py-epoll} "))
    assert "S_4^{\\mathrm{ft}}" in tex and "& 2.30 $\\pm$" in row and row.count(" & ") == 12


def test_gilbatch_and_load_tables(tmp_path):
    def cell(exp, engine, workers, rps, conns=400, **extra):
        return [{"experiment": exp, "engine": engine, "mode": "thread", "workers": workers,
                 "rps": v, "srv_gil": "on", "conns": conns, **extra} for v in (rps, rps)]
    rows = []
    for engine, acq, x4 in (("uringpy-app", 1000, 190e3), ("uringpy-app-batch1", 1000, 190e3),
                            ("uringpy-app-batch4", 250, 240e3), ("uringpy-app-batch", 20, 270e3)):
        rows += cell("gilbatch", engine, 1, 125e3, srv_handler_calls=1000, srv_gil_acquires=1000)
        rows += cell("gilbatch", engine, 4, x4, srv_handler_calls=1000, srv_gil_acquires=acq,
                     srv_gil_hold_ns=2_000_000, srv_gil_wait_ns=8_000_000,
                     srv_requests=1000, srv_nvcsw=acq)
    write_folder(tmp_path, "gilbatch-a", "gilbatch", "3.14.7 gil_on",
                 [dict(r) for r in rows])
    load = []
    for conns in (16, 400):
        load += cell("load", "py-epoll", 1, 100e3, conns, srv_requests=1000, srv_gil_releases=2000)
        load += cell("load", "py-epoll", 4, 50e3 if conns == 400 else 120e3, conns,
                     srv_requests=1000, srv_gil_releases=2000)
    # more connections than the server could hold open: kept on disk, left out
    load += cell("load", "py-epoll", 1, 90e3, 1600)
    load += [{"experiment": "load", "engine": "py-epoll", "mode": "thread", "workers": 4,
              "rps": "", "conns": 1600, "status": "no-start"}]
    write_folder(tmp_path, "load-a", "load", "3.14.7 gil_on", load)
    d = mt.Data(*mt.load(str(tmp_path)), results_dir=str(tmp_path))

    tex = mt.tab_gilbatch(d)
    rows = [line for line in tex.splitlines() if " & " in line and "\\\\" in line][1:]
    assert [r.split(" & ")[0] for r in rows] == ["---", "1", "4", "none"]
    assert [r.split(" & ")[1] for r in rows] == ["1.000", "1.000", "0.250", "0.020"]
    assert "2.16 $\\pm$" in rows[-1]                 # 270k over 125k
    # hold 2 us at 270k req/s: the GIL is in use for 54% of each second
    assert "& 2.00 & 8.00 & 0.54 & 0.020" in rows[-1]

    tex = mt.tab_load(d)
    assert "\\code{py-epoll} & 16 &" in tex and " & 400 & " in tex
    assert "1.20 $\\pm$" in tex and "0.50 $\\pm$" in tex
    assert " & 1600 & " not in tex and "3 runs with 1600 connections are not shown" in tex
    values = mt.numbers(d)
    assert values["S:load/g/py-epoll/thread/4/c16"] == "1.20"
    assert values["S:load/g/py-epoll/thread/4"] == "0.50"
    assert not any(key.endswith("/c1600") for key in values)
    assert values["meta:excluded-runs"] == "3" and values["meta:excluded-failed"] == "1"
    assert values["meta:failed"] == "0"
    assert values["meta:runs"] == "24" and values["meta:runs-made"] == "27"


def test_runs_made_later_with_raised_container_limits(tmp_path):
    def cell(exp, engine, mode, workers, rps, conns=400, **extra):
        return [{"experiment": exp, "engine": engine, "mode": mode, "workers": workers,
                 "rps": v, "srv_gil": "on", "conns": conns, **extra} for v in (rps, rps)]
    # the main run: 1600 connections under the default limit are left out
    main = (cell("load", "uringpy", "thread", 1, 140e3) + cell("load", "uringpy", "thread", 4, 320e3)
            + cell("load", "uringpy", "thread", 1, 130e3, 1600)
            + cell("load", "uringpy", "thread", 4, 150e3, 1600))
    write_folder(tmp_path, "load-a", "load", "3.14.7 gil_on", main)
    # the later run: the same cells with the open-file limit raised are kept
    later = (cell("load", "uringpy", "thread", 1, 100e3, 1600)
             + cell("load", "uringpy", "thread", 4, 250e3, 1600))
    write_folder(tmp_path, "load-b", "load", "3.14.7 gil_on", later, driver="1234567890",
                 docker_opts="--ulimit nofile=65536:65536 --ulimit memlock=-1:-1",
                 day="2026-10-08")
    loops = []
    for engine, x1, x4 in (("asyncio", 60e3, 30e3), ("uringcore", 80e3, 120e3)):
        loops += cell("loops", engine, "thread", 1, x1, srv_nvcsw=10)
        loops += cell("loops", engine, "thread", 4, x4, srv_nvcsw=int(x4 * 25))
    write_folder(tmp_path, "loops-b", "loops", "3.14.7 gil_on", loops, driver="1234567890",
                 image="uringpy:abcdef0-loops", docker_opts="--ulimit memlock=-1:-1")
    d = mt.Data(*mt.load(str(tmp_path)), results_dir=str(tmp_path))

    c = d.get("load", "on", "uringpy", "thread", 4, conns=1600)
    assert c.n == 2 and c.mean == 250e3                      # only the later runs
    tex = mt.tab_load(d)
    assert " & 1600 & " in tex and "2.50 $\\pm$" in tex
    assert "4 earlier runs" in tex and "limit on open files raised" in tex
    values = mt.numbers(d)
    assert values["meta:excluded-runs"] == "4" and values["S:load/g/uringpy/thread/4/c1600"] == "2.50"
    # the server code is the image's commit; the later driver commit is listed apart
    assert values["meta:commits"] == "abcdef0"
    assert values["meta:supplement-commits"] == "1234567" and values["meta:days"] == "2"

    tex = mt.tab_loops(d)
    row = next(line for line in tex.splitlines() if line.startswith("\\code{uringcore}"))
    assert "1.50 $\\pm$" in row and "& 1.000 &" in row       # one switch per request
    point, = mt._handoff_points(d)["uring_loops"]            # and a point of the figure
    assert point[:2] == (1.0, 1.5) and point[3] == "\\code{uringcore}"
    # without an io_uring loop the table would only repeat the scaling table
    other = tmp_path / "x"
    other.mkdir()
    assert mt.tab_loops(make_results(other)) is None
