"""Tests for benchmarks/make_tables.py: the paper's tables are computed from
raw runs, so the arithmetic is checked here on a small synthetic result set."""

import csv
import json
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "..", "benchmarks"))

import make_tables as mt  # noqa: E402

FIELDS = ["experiment", "engine", "mode", "workers", "resp_size", "max_batch", "handler_work",
          "status", "rps", "lat_p99_ms", "server_cpu_pct", "client_cpu_pct", "srv_requests",
          "srv_syscalls", "srv_enters", "srv_completions", "srv_gil", "transfer_mb_s",
          "srv_handler_calls", "srv_gil_hold_ns", "srv_gil_wait_ns", "srv_gil_acquires"]


def write_folder(root, name, experiment, interpreter, rows, nproc=4):
    d = root / name
    d.mkdir()
    (d / "meta.json").write_text(json.dumps(
        {"experiment": experiment, "server": {"interpreter": interpreter, "nproc": str(nproc)},
         "client": {"git_commit": "abcdef0123"}}))
    with open(d / "runs.csv", "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=FIELDS)
        w.writeheader()
        for r in rows:
            w.writerow({"experiment": experiment, "resp_size": 13, "max_batch": 0,
                        "handler_work": 0, "status": "ok", **r})


def runs(engine, mode, workers, values, **extra):
    return [{"engine": engine, "mode": mode, "workers": workers, "rps": v, **extra}
            for v in values]


def make_results(tmp_path):
    rows = (runs("uringpy", "thread", 1, [100e3, 102e3, 98e3], server_cpu_pct=25, srv_gil="on",
                 srv_requests=1000, srv_syscalls=10, srv_enters=10, srv_completions=2000)
            + runs("uringpy", "thread", 4, [300e3, 300e3, 300e3], server_cpu_pct=100, srv_gil="on")
            + [{"engine": "uringpy", "mode": "thread", "workers": 4, "rps": "",
                "status": "no-start"}])
    write_folder(tmp_path, "scaling-a", "scaling", "3.14.7 gil_on", rows)
    write_folder(tmp_path, "scaling-b", "scaling", "3.14.7 gil_OFF",
                 runs("uringpy", "thread", 1, [90e3, 90e3], srv_gil="off"))
    (tmp_path / "not-a-result").mkdir()
    return mt.Data(*mt.load(str(tmp_path)))


def test_load_groups_by_gil_and_skips_failed_runs(tmp_path):
    d = make_results(tmp_path)
    c1 = d.get("scaling", "on", "uringpy", "thread", 1)
    c4 = d.get("scaling", "on", "uringpy", "thread", 4)
    assert c1.n == 3 and abs(c1.mean - 100e3) < 1e-6
    assert c4.n == 3 and c4.failed == 1          # the failed run is counted, not averaged
    assert d.get("scaling", "off", "uringpy", "thread", 1).n == 2
    assert [f["gil"] for f in d.folders] == ["on", "off"]


def test_derived_quantities(tmp_path):
    d = make_results(tmp_path)
    c1 = d.get("scaling", "on", "uringpy", "thread", 1)
    c4 = d.get("scaling", "on", "uringpy", "thread", 4)
    assert c1.busy_cores == 1.0 and c4.busy_cores == 4.0     # 25% and 100% of 4 cores
    assert abs(c1.per_core - 100e3) < 1e-6
    assert abs(mt._efficiency(c1, c4) - 0.75) < 1e-9          # 75k per core / 100k per core
    assert c1.syscalls_per_request == 30 / 3000
    assert c1.completions_per_enter == 200.0
    # half-width: t(0.975, 2) * s / sqrt(3) with s = 2000
    assert abs(c1.hw - 4.303 * 2000 / 3 ** 0.5) < 1e-6


def test_tables_are_written_and_carry_the_numbers(tmp_path):
    d = make_results(tmp_path)
    tex = mt.tab_scaling(d)
    assert "\\label{tab:scaling}" in tex
    assert "100.0 $\\pm$ 5.0" in tex and "300.0 $\\pm$ $<$0.1" in tex
    assert "3.00 $\\pm$" in tex                    # S_4
    assert mt.tab_app(d) is None                   # no data for that experiment
    out = tmp_path / "out"
    assert mt.main(["--results", str(tmp_path), "--out", str(out)]) == 0
    assert (out / "tab_scaling.tex").read_text().startswith("% Generated by")
    assert not (out / "tab_app.tex").exists()


def test_handler_table_derives_f_and_bound(tmp_path):
    def cell(engine, mode, workers, rps, **extra):
        return [{"engine": engine, "mode": mode, "workers": workers, "rps": v,
                 "handler_work": 300, "srv_gil": "on", **extra} for v in (rps, rps)]
    rows = (cell("uringpy-app", "thread", 1, 50e3, srv_handler_calls=1000,
                 srv_gil_hold_ns=10_000_000, srv_gil_wait_ns=0, srv_gil_acquires=1000)
            + cell("uringpy-app", "thread", 2, 75e3)
            + cell("uringpy-app", "thread", 4, 80e3, srv_handler_calls=1000,
                   srv_gil_hold_ns=12_000_000, srv_gil_wait_ns=30_000_000,
                   srv_gil_acquires=250)
            + cell("uringpy-app", "process", 1, 50e3) + cell("uringpy-app", "process", 4, 150e3))
    write_folder(tmp_path, "handler-a", "handler", "3.14.7 gil_on", rows)
    d = mt.Data(*mt.load(str(tmp_path)))
    t1 = d.get("handler", "on", "uringpy-app", "thread", 1, work=300)
    t4 = d.get("handler", "on", "uringpy-app", "thread", 4, work=300)
    assert t1.gil_hold_us == 10.0                 # 10 ms over 1000 calls
    assert t4.gil_wait_us == 30.0 and t4.acquires_per_request == 0.25
    tex = mt.tab_handler(d)
    # t_p = 10 us at 50k req/s -> f = 0.50 -> bound 2.00; S_2 = 1.50, S_4 = 1.60, processes 3.00
    row = next(line for line in tex.splitlines() if line.startswith("request & 300"))
    assert "& 10.00 & 0.50 & 2.00 &" in row
    assert "1.50 $\\pm$" in row and "1.60 $\\pm$" in row and "3.00 $\\pm$" in row
    # at four threads: hold 12 us, wait 30 us, 0.25 acquisitions per call,
    # GIL utilisation 12 us * 80k req/s = 0.96
    assert row.rstrip(" \\").endswith("& 12.00 & 30.00 & 0.250 & 0.96")
